### ISSUE TITLE
Latest version of crawler broken

### ISSUE THREAD

**Issue by connecteev** [kiliman/tailwindui-crawler#22]
After a fresh git pull, this is what I see:

$ yarn start
yarn run v1.22.0
$ node index.js
🔐  Logging into tailwindui.com...
✅  Success!

🗂   Output is ../tailwindui_output
⏳  Processing /components/marketing/sections/heroes...
‼️   /TAILWINDUI/tailwindui_crawler_kiliman/crawler/transformers/prefixClasses/tailwind-classes.js:2
export default {
^^^^^^
SyntaxError: Unexpected token 'export'
    at wrapSafe (internal/modules/cjs/loader.js:1067:16)
    at Module._compile (internal/modules/cjs/loader.js:1115:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1171:10)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14)
    at Module.require (internal/modules/cjs/loader.js:1040:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/TAILWINDUI/tailwindui_crawler_kiliman/crawler/transformers/prefixClasses/index.js:3:21)
    at Module._compile (internal/modules/cjs/loader.js:1151:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1171:10)
✨  Done in 1.78s.

**Comment by kiliman** [comment]
Sorry. Merged in a PR without testing it. The syntax works fine for the browser, but not for node.js.

Anyway, this is fixed.

**Comment by connecteev** [comment]
Verified this works now. Thanks for the quick update!
