### ISSUE TITLE
Syntax error?

### ISSUE THREAD

**Issue by key88sf** [kiliman/tailwindui-crawler#73]
```
yarn run v1.22.15
$ node index.mjs
file:///Users/xxx/workspace/tailwindui-crawler/index.mjs:79
      port: uri.port ?? 443,
                      ^

SyntaxError: Unexpected token '?'
    at Loader.moduleStrategy (internal/modules/esm/translators.js:140:18)
    at async link (internal/modules/esm/module_job.js:42:21)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by key88sf** [comment]
Looks like there is a minimum `node` version required? I updated to Node 16x and that works now.

**Comment by kiliman** [comment]
Oops, sorry. It looks like nullish coalescing operator (`??`) is only supported on Node v14.5+. I need to update _package.json_ to specify the version. Thanks!

https://node.green/#ES2020-features--nullish-coalescing-operator-----
