### ISSUE TITLE
bug: new tailwindui structure

### ISSUE THREAD

**Issue by Barabazs** [kiliman/tailwindui-crawler#89]
It seems like the tailwindui structure has changed

```
🗂   Output is /output/./
🔍  Fetching https://tailwindui.com/components
⏱   164ms (200)
⏳  Processing #1: https://tailwindui.com/components/marketing/sections/heroes...
🔍  Fetching https://tailwindui.com/components/marketing/sections/heroes
⏱   172ms (200)
🔍  Found 12 components
‼️   TypeError: Cannot read properties of undefined (reading 'forEach')
    at processComponent (file:///crawler/index.mjs:249:22)
    at processComponentPage (file:///crawler/index.mjs:221:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async file:///crawler/index.mjs:460:26
```
These are the current properties of component:
```
   properties: [
    'name',
    'uuid',
    'isNew',
    'downloadable',
    'imageCreditsHtml',
    'requiresJavaScript',
    'archived',
    'iframeHtml',
    'snippet',
    'largeWidth',
    'largeHeight',
    'smallWidth',
    'smallHeight'
  ]
```
component.snippet only contains the default or previously selected language.

**Comment by kiliman** [comment]
Yeah, they changed the structure to accommodate Tailwind 3.x and 4. I haven't had a chance to play with it. PRs are definitely welcome.

I might be able to check during the holiday break.
